version: "3"
services:
  context-db:
    image: mongo:3.6
    hostname: context-db
    container_name: context-db
    expose:
        - "27017"
    ports:
        - "27017:27017"
    networks:
        - my-net
    command: --bind_ip_all --smallfiles

  orion:
    image: fiware/orion:latest
    hostname: orion
    container_name: orion
    depends_on:
      - context-db
    networks:
        - my-net
    expose:
        - "1026"
    ports:
        - "1026:1026"
    command: -dbhost context-db -logLevel DEBUG

networks:
  my-net: